
# Site title
title: Memoizer
description: Articles of this website is notes for oneself.
baseurl: ""

words_per_minute: 120

# Authors
author:
  name: yatanokarasu

# Build settings
markdown: kramdown

paginate: 5

menus:
  - title:  'Home'
    url:    '/'
    icon:   'home'
  - title:  'Archives'
    url:    '/archives'
    icon:   'archive'
  - title:  'Categories'
    url:    '/categories'
    icon:   'folder-open'
  - title:  'Tags'
    url:    '/tags'
    icon:   'tags'
  - title:  'About'
    url:    '/about'
    icon:   'question-circle'


gems:
  - jekyll-paginate
  - jekyll-gist

sass:
  sass_dir: _scss
  style: compressed

exclude:
  - README.md
  - LICENSE
