
# Site title
title: Memoizer
description: Articles of this website is notes for oneself.
baseurl: ""

words_per_minute: 120

# Authors
author:
  name: yatanokarasu

# Menu
menus:
  - title:  'Home'
    url:    '/'
  - title:  'Categories'
    url:    '/categories'
  - title:  'Tags'
    url:    '/tags'
  - title:  'About'
    url:    '/about'

# Build settings
markdown: kramdown

paginate: 5

gems:
  - jekyll-paginate

sass:
  sass_dir: _scss
  style: compressed

exclude:
  - README.md
  - LICENSE
