
# Site title
title: Memoizer
baseurl: ""

words_per_minute: 200

# Authors
author:
    github:     yatanokarasu

# Build settings
markdown: kramdown

paginate:   5

gems:
    - jekyll-paginate
